### PR TITLE
Update Dockerfile to use the latest Crystal image

### PR DESCRIPTION
**Pull request by Sija**

### CODE REVIEW

**Comment by paulcsmith** [comment]
I'm guessing the chromedriver binaries need to be updated: https://github.com/luckyframework/lucky_flow/tree/master/vendor

See https://github.com/edwardloveall/lucky_bits/pull/51

**Comment by Sija** [comment]
@paulcsmith 👍 I'd suggest doing that in a separate PR though.

**Comment by paulcsmith** [comment]
Could rename master and force push? I think that’ll get it passing

**Comment by Sija** [comment]
_rename master_, WDYM?

**Comment by paulcsmith** [comment]
I meant rebase. Autocorrect issues ;)

**Comment by Sija** [comment]
I would prefer not to, my local clone is broken and this is a clean merge anyway...

**Comment by paulcsmith** [comment]
Ah ok. Will merge as is! Thanks

**Comment by Sija** [comment]
I'd suggest making a new patch release.

**Comment by paulcsmith** [comment]
Already released yesterday :D It doesn't have this Docker fix but that's for testing anyway

**Comment by paulcsmith** [comment]
Actually it'd be nice to have that Chromedriver update too. I'll release another!

**Pull request merged**
